// This file is generated by openapi-ts
// Run `npm run openapi-ts` to regenerate

// Temporary exports until OpenAPI schema is generated
export const OpenAPI = {
  interceptors: {
    request: {
      // biome-ignore lint/suspicious/noExplicitAny: Temporary placeholder
      use: (_interceptor: (request: any) => any) => {
        // Placeholder implementation
      },
    },
  },
};

export const UsersService = {
  usersList: async () => {
    // Placeholder implementation
    return { results: [] };
  },
};

export const RestService = {
  ...UsersService,
  restRestCheckRetrieve: async () => {
    // Placeholder implementation for API check endpoint
    return { status: 'ok', message: 'API is working' };
  },
};
