// This file is auto-generated by @hey-api/openapi-ts

import type { CancelablePromise } from './core/CancelablePromise';
import { OpenAPI } from './core/OpenAPI';
import { request as __request } from './core/request';
import type {
  RestRestCheckRetrieveResponse,
  UsersCreateData,
  UsersCreateResponse,
  UsersDestroyData,
  UsersDestroyResponse,
  UsersListData,
  UsersListResponse,
  UsersPartialUpdateData,
  UsersPartialUpdateResponse,
  UsersRetrieveData,
  UsersRetrieveResponse,
  UsersUpdateData,
  UsersUpdateResponse,
} from './types.gen';

export class RestService {
  /**
   * Check REST API
   * This endpoint checks if the REST API is working.
   * @returns Message
   * @throws ApiError
   */
  public static restRestCheckRetrieve(): CancelablePromise<RestRestCheckRetrieveResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/rest/rest-check/',
    });
  }
}

export class UsersService {
  /**
   * @param data The data for the request.
   * @param data.limit Number of results to return per page.
   * @param data.offset The initial index from which to return the results.
   * @returns PaginatedUserList
   * @throws ApiError
   */
  public static usersList(data: UsersListData = {}): CancelablePromise<UsersListResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/users/',
      query: {
        limit: data.limit,
        offset: data.offset,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static usersCreate(data: UsersCreateData): CancelablePromise<UsersCreateResponse> {
    return __request(OpenAPI, {
      method: 'POST',
      url: '/api/users/',
      body: data.requestBody,
      mediaType: 'application/json',
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @returns User
   * @throws ApiError
   */
  public static usersRetrieve(data: UsersRetrieveData): CancelablePromise<UsersRetrieveResponse> {
    return __request(OpenAPI, {
      method: 'GET',
      url: '/api/users/{id}/',
      path: {
        id: data.id,
      },
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static usersUpdate(data: UsersUpdateData): CancelablePromise<UsersUpdateResponse> {
    return __request(OpenAPI, {
      method: 'PUT',
      url: '/api/users/{id}/',
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: 'application/json',
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @param data.requestBody
   * @returns User
   * @throws ApiError
   */
  public static usersPartialUpdate(
    data: UsersPartialUpdateData
  ): CancelablePromise<UsersPartialUpdateResponse> {
    return __request(OpenAPI, {
      method: 'PATCH',
      url: '/api/users/{id}/',
      path: {
        id: data.id,
      },
      body: data.requestBody,
      mediaType: 'application/json',
    });
  }

  /**
   * @param data The data for the request.
   * @param data.id A unique integer value identifying this user.
   * @returns void No response body
   * @throws ApiError
   */
  public static usersDestroy(data: UsersDestroyData): CancelablePromise<UsersDestroyResponse> {
    return __request(OpenAPI, {
      method: 'DELETE',
      url: '/api/users/{id}/',
      path: {
        id: data.id,
      },
    });
  }
}
