import json
import os

from django import template
from django.conf import settings
from django.utils.safestring import mark_safe


register = template.Library()


@register.simple_tag
def render_vite_bundle(bundle_name="main", bundle_type="js", config="DEFAULT"):
    """
    Renders Vite bundles in development and production.
    Maintains compatibility with webpack_loader API.
    """
    dev_mode = settings.DEBUG

    if dev_mode:
        # In development, load from Vite dev server
        if bundle_type == "js":
            return mark_safe(
                '<script type="module" src="http://localhost:3000/frontend/js/index.tsx"></script>'
            )
        # CSS is handled by Vite in development
        return ""

    # In production, read from webpack-stats.json (generated by Vite)
    stats_file = os.path.join(settings.BASE_DIR, "../webpack-stats.json")

    try:
        with open(stats_file) as f:
            stats = json.load(f)
    except (FileNotFoundError, json.JSONDecodeError):
        return ""

    if stats.get("status") != "done":
        return ""

    html = []
    chunks = stats.get("chunks", {}).get(bundle_name, [])

    for chunk in chunks:
        if bundle_type == "js" and chunk["name"].endswith(".js"):
            html.append(f'<script type="module" src="{chunk["path"]}"></script>')
        elif bundle_type == "css" and chunk["name"].endswith(".css"):
            html.append(f'<link rel="stylesheet" href="{chunk["path"]}">')

    # Also check assets for CSS files
    if bundle_type == "css":
        for asset_name, asset_info in stats.get("assets", {}).items():
            if asset_name.endswith(".css"):
                html.append(f'<link rel="stylesheet" href="{asset_info["path"]}">')

    return mark_safe("\n".join(html))
